.onAttach<- function(libname, pkgname) {
  packageStartupMessage(
  "
         __      _             ___
         )_)    /_)    )\\/)    )_     )\\  )
        / \\    / /    (  (    (__    (  \\(

                  (   )  (  (
                 (  ( )  (  )
                   )    )  (
                _.(--'(''--.._
               /, _..-----).._,\\
              |  `'''-----'''`  |
               \\               /
                '.           .'
                  '--.....--'

If you use RAMEN for your analysis, please cite Navarro-Delgado EI., et al. (2025).", domain = NULL, appendLF = TRUE)
} #ASCII letters were generated by https://ascii.co.uk/text; the bowl was taken from http://www.geocities.ws/SoHo/7373/food.html and modified
